name: 'Pipeline do Pedro Golino'

on:
  workflow_dispatch:
    inputs:
      acao:
        type: string
        required: true
        description: 'Ação'
      valor:
        type: string
        required: true
        description: 'Valor'

jobs:
  nome_job_1:
    runs-on: ubuntu-latest
    name: 'Nome Job 1'
    steps:
      - id: checkout
        name: 'Checkout Repository'
        uses: actions/checkout@v3
      - id: configurar_node
        name: 'Configurar Node'
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: instalar_pacotes
        name: 'Instalar Pacotes'
        shell: bash
        run: |
          cd "${{ github.workspace }}/src"
          npm install
      - id: rodar_eslint
        name: 'Rodar ESLint'
        shell: bash
        run: |
          cd "${{ github.workspace }}/src"
          npm run lint
